### ISSUE TITLE
Warning: You are using a version of node-ipc containing malicious code 

### ISSUE THREAD

**Issue by lukas-mertens** [alankrantas/vueapp-typescript-express#1]
I just wanted to warn you about a current version of node-ipc containing https://github.com/RIAEvangelist/peacenotwar. You should probably pin your dependencies. It was classified as 9.8/10 severity by snyk.

You can read more about it here:
https://github.com/RIAEvangelist/node-ipc/issues/233
https://security.snyk.io/vuln/SNYK-JS-NODEIPC-2426370

**Comment by alankrantas** [comment]
Thanks, I upgraded ```@Vue/Cli``` to 5.0.3 and now it shows ```npm-ipc``` is locked to 9.2.1.
